import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../core/app_constants.dart';

part 'quran_database.g.dart';

@DataClassName('Surah')
class Surahs extends Table {
  IntColumn get id => integer()(); // 1..114
  TextColumn get nameArabic => text()();
  TextColumn get nameLatin => text()();
  TextColumn get nameIndonesian => text()();
  IntColumn get revelationType => integer()(); // 0=Makki, 1=Madani
  IntColumn get ayahCount => integer()();
  IntColumn get firstJuz => integer()();
  IntColumn get firstPage => integer()();
  IntColumn get hasBismillah => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('Ayah')
@TableIndex(name: 'idx_ayahs_juz', columns: {#juz})
class Ayahs extends Table {
  IntColumn get id => integer()(); // global 1..6236
  IntColumn get surahId => integer()();
  IntColumn get ayahNumber => integer()();
  TextColumn get textUthmani => text()();
  TextColumn get translation => text()();
  IntColumn get juz => integer()();
  IntColumn get page => integer()();
  IntColumn get sajda => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};

  @override
  List<Set<Column>> get uniqueKeys => [{surahId, ayahNumber}];
}

@DataClassName('Tafsir')
class Tafsirs extends Table {
  // Canonical SQL name (tool/build_db.py schema). Drift's default snake_case
  // of `Tafsirs` would be `tafsirs`, which would fail the on-open schema
  // validation against the prebuilt DB.
  @override
  String get tableName => 'tafsir';

  IntColumn get ayahId => integer()();
  TextColumn get textShort => text()();
  TextColumn get textLong => text()();

  @override
  Set<Column> get primaryKey => {ayahId};
}

/// The prebuilt reference database (read-only at runtime).
///
/// Bundled as `assets/db/quran.db`, copied atomically on first run and on
/// schema-version mismatch (`replace-on-version-mismatch`, never migrated).
/// The FTS5 virtual table `ayah_fts` is NOT a drift table — query it via
/// `customSelect` (see SearchRepository).
@DriftDatabase(tables: [Surahs, Ayahs, Tafsirs])
class QuranDatabase extends _$QuranDatabase {
  /// `executor` is injectable for tests; production uses the bundled asset.
  QuranDatabase({QueryExecutor? executor}) : super(executor ?? _open());

  @override
  int get schemaVersion => AppConstants.quranDbSchemaVersion;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => throw StateError(
            'quran.db is prebuilt; onCreate must never run (copy-on-version-mismatch handles it)'),
        onUpgrade: (m, from, to) => throw StateError(
            'quran.db is regenerated by tool/build_db.py; onUpgrade must never run'),
      );

  /// Reads bytes 60-63 of the SQLite header (big-endian user version) without
  /// opening a connection.
  static int _readUserVersion(File file) {
    final raf = file.openSync(mode: FileMode.read);
    try {
      raf.setPositionSync(60);
      final buf = raf.readSync(4);
      if (buf.length < 4) return 0;
      return (buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3];
    } catch (e) {
      debugPrint('QuranDatabase._readUserVersion: failed to read header — $e');
      return 0;
    } finally {
      raf.closeSync();
    }
  }

  static QueryExecutor _open() {
    return LazyDatabase(() async {
      final dir = Directory(p.join(
          (await getApplicationSupportDirectory()).path, AppConstants.dbSubDir));
      await dir.create(recursive: true);
      final file = File(p.join(dir.path, AppConstants.quranDbFile));

      final exists = file.existsSync();
      final versionOk =
          exists && _readUserVersion(file) == AppConstants.quranDbSchemaVersion;
      if (!versionOk) {
        final data =
            await rootBundle.load(AppConstants.quranDbAsset); // asset copied at build time
        final bytes =
            data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
        // Drop stale WAL sidecars: a leftover -wal/-shm from a previous,
        // differently-versioned database would be replayed onto the fresh
        // file and corrupt it on open.
        for (final suffix in const ['-wal', '-shm']) {
          final side = File('${file.path}$suffix');
          if (side.existsSync()) side.deleteSync();
        }
        final tmp = File('${file.path}.tmp');
        await tmp.writeAsBytes(bytes, flush: true);
        if (exists) file.deleteSync();
        await tmp.rename(file.path); // atomic-ish replace
        await _quickCheck(file);
      }

      return NativeDatabase.createInBackground(
        file,
        setup: (db) => db.execute('PRAGMA journal_mode = WAL'),
      );
    });
  }

  static Future<void> _quickCheck(File file) async {
    final db = NativeDatabase(file);
    try {
      final rows = await db.runSelect('PRAGMA quick_check', const []);
      final ok = rows.isNotEmpty && rows.first['quick_check'] == 'ok';
      if (!ok) throw StateError('quran.db quick_check failed');
    } finally {
      await db.close();
    }
  }
}
